### ISSUE TITLE
nodeTransform is not always flushing its output queue

### ISSUE THREAD

**Issue by bjouhier** [Sage/ez-streams#27]

**Comment by emueller-sage** [comment]
Dear Bruno,
thank you very much for this change. I will do some test and inform you on Monday so that the branch can be merged.
Best regards
Eric

Von: Bruno Jouhier [mailto:notifications@github.com]
Gesendet: Freitag, 16. Januar 2015 14:32
An: Sage/ez-streams
Betreff: Re: [ez-streams] nodeTransform is not always flushing its output queue (#27)


Closed #27<https://github.com/Sage/ez-streams/issues/27> via 08a6cc2<https://github.com/Sage/ez-streams/commit/08a6cc24bb2ef5b8d0e807bca3dcbe6ec89b565a>.

—
Reply to this email directly or view it on GitHub<https://github.com/Sage/ez-streams/issues/27#event-220066745>.

Sage bäurer GmbH-Sitz: Donaueschingen, Handelsregister: Freiburg i. Br. HRB

611793, Geschaeftsfuehrer: Dr. Thomas Scholtis

-----------------Disclaimer-----------------

Die in dieser E-Mail und den dazu gehoerigen Anhaengen (die Nachricht) enthaltenen Informationen sind nur fuer den Adressaten bestimmt und koennen vertrauliche und/oder rechtlich geschuetzte Informationen enthalten. Sollten Sie die Nachricht irrtuemlich erhalten haben, loeschen Sie die Nachricht bitte und benachrichtigen Sie den Absender, ohne die Nachricht zu kopieren oder zu verteilen oder ihren Inhalt an andere Personen weiterzugeben. Ausser bei Vorsatz oder grober Fahrlaessigkeit schliessen wir jegliche Haftung fuer Verluste oder Schaeden aus, die durch virenbefallene Software oder E-Mails verursacht werden.

-----------------Disclaimer-----------------

The information contained in this e-mail and any attachments (the message) is intended for the addressee only and may contain confidential and/or privileged information. If you have received the message by mistake please delete it and notify the sender and do not copy or distribute it or disclose its contents to anyone. Except in case of gross negligence or wilful misconduct we accept no liability for any loss or damage caused by software or e-mail viruses.
